global:
  scrape_interval: 10s

rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'node_backend'
    static_configs:
      - targets: ['backend:3000']

  - job_name: 'mysql_exporter'
    params:
      collect[]:
      - foo
      - bar 
    static_configs:
      - targets:
          - 'mysql-exporter:9104'
        labels:
          service: mysql_exporter
          environment: production
          version: 0.12.1
  
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'
          - 'nginx-exporter:9113'
          
        labels:
          service: node_exporter
          environment: production
          version: 1.3.1

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: 'phpmyadmin'
    static_configs:
      - targets:
          - 'phpmyadmin:80'
        labels:
          service: phpmyadmin
          environment: production
          version: 5.1
